# Generated by Django 4.2.25 on 2025-10-15 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('destination', models.CharField(max_length=255)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('receiver_name', models.CharField(blank=True, max_length=255)),
                ('items', models.JSONField(blank=True, default=list)),
                ('document_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
