# Generated by Django 4.2.26 on 2025-11-12 13:16

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="levies",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
